export { default as ArrowDoubleLeftIcon } from './ArrowDoubleLeftIcon.vue'
export { default as ArrowDoubleRightIcon } from './ArrowDoubleRightIcon.vue'
export { default as ArrowLeftIcon } from './ArrowLeftIcon.vue'
export { default as ArrowRightIcon } from './ArrowRightIcon.vue'
export { default as ChevronDownIcon } from './ChevronDownIcon.vue'
export { default as ChevronUpIcon } from './ChevronUpIcon.vue'
export { default as WrapperPages } from './WrapperPages.vue'
